apiVersion: apps/v1
kind: Deployment
metadata:
  name: sorteos-live-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sorteos-live
  template:
    metadata:
      labels:
        app: sorteos-live
    spec:
      containers:
        - name: sorteos-live
          image: 10.1.10.13:5000/sorteos-live:v1.0.0
          ports:
            - containerPort: 80
          imagePullPolicy: Always
