apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sorteos-live-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: "nginx-interno"
  tls:
    - hosts:
        - sorteos-live.coopetarrazu.dev
      secretName: sorteos-live-tls-secret
  rules:
    - host: sorteos-live.coopetarrazu.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sorteos-live-svc
                port:
                  number: 80
