apiVersion: v1
kind: Service
metadata:
  name: ms-acciones-tareas-svc
spec:
  type: ExternalName
  externalName: ms-acciones-tareas-svc.sorteos.svc.cluster.local
  ports:
    - port: 80
      targetPort: 80
