apiVersion: v1
kind: Service
metadata:
  name: sorteos-live-svc
spec:
  type: ClusterIP
  selector:
    app: sorteos-live
  ports:
    - protocol: TCP
      name: main
      port: 80
      targetPort: 80
